### ISSUE TITLE
Encoding issue in README output

### ISSUE THREAD

**Issue by jonathanKingston** [hegemonic/jsdoc-baseline#134]
As mentioned in the JSDOC issue: https://github.com/jsdoc3/jsdoc/issues/913#issuecomment-73431391

There is an issue with the HTML encoding of the home page where by the output is HTML escaped.

**Comment by jonathanKingston** [comment]
Even standard markdown was coming out as escaped HTML too which I am sure is not the intention here.

**Comment by hegemonic** [comment]
Thanks for the heads up! I can merge your pull request once you've signed the CLA.

**Comment by jonathanKingston** [comment]
@hegemonic I sent it over the other day with the requests, let me know if there are any issues.

**Comment by hegemonic** [comment]
Sorry for the delay in looking at these. I merged this to master. Thanks for the fix!
