### ISSUE TITLE
When loading templates over https the output loads insecure fonts

### ISSUE THREAD

**Issue by jonathanKingston** [hegemonic/jsdoc-baseline#136]
When loading templates over https the output loads insecure fonts.

The solution should probably be changing the protocol to `//brick...`

**Comment by hegemonic** [comment]
@jonathanKingston Did you confirm that your change fixes the problem? Also, can you please [sign the CLA](https://github.com/hegemonic/jsdoc-baseline/blob/master/CONTRIBUTING.md) and let me know when you've done so?

**Comment by jonathanKingston** [comment]
@hegemonic have sent over, let me know if it did not come through.

Confirmed it works by this: https://jetson.io

Which is generated from: https://github.com/jonathanKingston/jsdoc-baseline/tree/jetson-release

That is the combination of this issue and #134 

Thanks

**Comment by hegemonic** [comment]
Merged to master--thanks!

**Comment by jonathanKingston** [comment]
:+1: thank you

**Comment by hegemonic** [comment]
Sorry, but I had to revert your pull request. It broke font loading when you're viewing the output files locally, through a `file://` URL.

I agree that this is a bug, but we'll need to come up with a better fix.

**Comment by jonathanKingston** [comment]
Sorry I should have mentioned that was one of the limitations. The way I have resolved this in the past is by using a script to check which environment the page is running in. However I think this doesn't fit with the paradigm we are in here.

I am going to submit a pull request which is hard coded to always be https which will work in all environments, it has the slight disadvantage of putting excessive load on the font service when in http and local however that to me isn't really a valid issue any more (I'm happy to be told otherwise though :D )

Thanks

**Comment by hegemonic** [comment]
Good thinking! I merged the pull request to master. Thanks for taking another shot at this.

**Comment by jonathanKingston** [comment]
:+1: thanks, only just seen this.
