### ISSUE TITLE
Method description has an arrow pointing to "unknown"

### ISSUE THREAD

**Issue by kpturner** [hegemonic/jsdoc-baseline#143]
Each of my methods (in the generated documentation) has an arrow next to the description pointing to a piece of text saying "unknown". For example:

getJson(LazyLoader, File, Type, Field[, Program][, rplvars][, additionalText]) → unknown 

What causes that?   Am I missing something in my comments that jsdoc is expecting to find?

**Comment by hegemonic** [comment]
@kpturner I would expect this to happen if the method's return type is `{?}`. Is that the case?

If not, can you provide some sample code that results in this output?

**Comment by kpturner** [comment]
Right - so this is something that my old template didn'e care about.  My comments say:

          * @return String
 but from your response I gatherthis should be 
          * @return {String}

I have a lot of code to change :(

It is only the first section that looks wrong.  Under the parameters section is still correctly says
return String
regardless of which option I use to comment it.

**Comment by hegemonic** [comment]
Because the braces are missing, JSDoc is treating `String` as a description of the return value, rather than as the return type.

I think I'll address this by changing the Baseline template so that if the return type is missing, it just omits the type from the method signature, rather than saying `-> unknown`.

**Comment by kpturner** [comment]
Ok that sounds like a good compromise. I guess the other option would be that if you have "String" and no braces and no other text, then String must be the return type. From my perspective, since I like the idea Ofvthe return type being documented with the arrow, that would be even better :)

**Comment by hegemonic** [comment]
Compromise is now available on master. ;)

**Comment by kpturner** [comment]
I cannot seem to get this fix.  Please bear with me because I am new to git - so I assumed I would need to do a pull to get the fix (which I did).  However, on my system I cannot seem to use the jsdoc-baseline template with the version I pulled with git - I think that may be because that version is using Rhino.  However, I can use the jsdoc-baseline with the node version of jsdoc, which I obtained using:
npm install jsdoc@"<=3.3.0" -g
when I run with that, this problem still exists.
How to I get the fix for the node version?

Which compromise did you opt for by the way - yours or mine?  :)

**Comment by kpturner** [comment]
Ahh, just realised this was a fix to the baseline template - not jsdoc itself. I will try it later....

**Comment by kpturner** [comment]
So I did that - and now I cannot generate any docs at all:

FATAL: Unable to load template: Cannot find module 'underscore-contrib'

What have I done wrong?

**Comment by hegemonic** [comment]
I opted for my compromise, because your proposal would have required a possibly breaking change to JSDoc.

It sounds like one of three things is happening:

1. You're running the Rhino version of JSDoc on Windows and running into a known bug.
2. Baseline's submodules are not installed.
3. JSDoc's submodules are not installed.

I'd suggest reinstalling Baseline and JSDoc, then trying again. If you install Baseline by cloning the git repo, don't forget to run `npm install` afterwards.

**Comment by kpturner** [comment]
I am running on an IBMi so nothing is quite as it seems to Unix and Windows folks :) ....but anyway, I installed JSDOC like this:

npm install jsdoc@"<=3.3.0" -g
I then installed jsdoc-baseline like this:
npm install --save-dev https://github.com/hegemonic/baseline/tarball/master -g

then it works.

However, ideally, I would like to not do the second step at all and install jsdoc-baseline elsewhere in my directory structure (using git) and run the node version of jsdoc with that instead.

That is where it went pear shaped. So following your last instruction, if my git clone is in a folder structure like this:
/rn6/jsdoc-templates/jsdoc-baseline
can you tell me what the npm install command will look like to enable that to work? Am I supposed to do this:
npm install /rn6/jsdoc-templates/jsdoc-baseline -g

?  (yes I am a git and node noob :) )

**Comment by kpturner** [comment]
Yes is the answer to my own question having tried it :)
