### ISSUE TITLE
Method is appearing as a class on the homepage

### ISSUE THREAD

**Issue by kpturner** [hegemonic/jsdoc-baseline#144]
I have a peculiar situation where I have a top level class called RNS, but the methods within that class are not appearing underneath it. Instead the all appear underneath something that is not a class but a method.  I have tried to illustrate below.  I have node idea what is causing it though. This doesn't happen with my old template.  So class RNS has many methods, including RNS.base64Decode, but all its methods (including RNS.base64Decode) appear erroneously under a heading of RNS.base64Decode. 

![image](https://cloud.githubusercontent.com/assets/308646/6536543/518399d2-c446-11e4-907e-6e602fb04ad5.png)

**Comment by hegemonic** [comment]
Thanks for pointing this out. There's something funky going on with the code that groups things for `index.html`. I'll investigate.

**Comment by kpturner** [comment]
I should also say that if I only generate the source for the RNS class (it is all in one file) then I don't see this behavior. It is only when I generate the docs for everything - all of which hangs of the RNS class or namespace.

**Comment by hegemonic** [comment]
I can (approximately) reproduce this issue with the following source file:

```js
/**
 * Foo class.
 * @class
 */
function Foo() {}

/**
 * Do a thing.
 */
Foo.prototype.doThing = function() {};

/**
 * Bar namespace.
 * @namespace
 */
Foo.Bar = {
    /**
     * Get a widget.
     */
    getWidget: function() {}
};
```

**Comment by kpturner** [comment]
Yes I concur that this produces the same effect.

**Comment by hegemonic** [comment]
This should be fixed on master. Please take a look. If there's anything that still looks weird, I'd be happy to reopen this issue.
