### ISSUE TITLE
Source links and tags that don't appear to work

### ISSUE THREAD

**Issue by kpturner** [hegemonic/jsdoc-baseline#146]
A question about the source file links. I think these are very useful, but the only thing I have noticed is that the links appear to want to try to take you to a tag. In other words, if I click on a source link for a method that starts at line 100 then the URL looks like it is going to try to position me to line 100 when I click the link. The trouble is, it doesn't position me to line 100. Regardless of the URL, I am always position at the top of the source file. This is using Google Chrome.

**Comment by hegemonic** [comment]
Confirmed (belatedly). This appears to be the fault of `scrollanchor.js`. I'll investigate further.

**Comment by hegemonic** [comment]
Fixed on master. The fix should work across browsers, but if you run into this problem again, please feel free to file a new bug.

**Comment by hegemonic** [comment]
In another bug, @kpturner says: "Works OK in Firefox. Works in IE 11 (but very slow). Doesn't work in Chrome or Opera or Safari :("

Reopening while I investigate.

**Comment by hegemonic** [comment]
I've never been able to reproduce this issue, so I'm closing it.
