### ISSUE TITLE
Customising look and feel

### ISSUE THREAD

**Issue by kpturner** [hegemonic/jsdoc-baseline#147]
Not really an issue, but more of a request for information.

What is the recommended method for customising the look and feel without losing the customisations when updates are pulled?

I specifically just want to add a logo to the left of the "Home" link to start with.

**Comment by hegemonic** [comment]
The (work-in-progress) docs are here: https://docs.google.com/document/d/1H26OrUaP0RFU_envNq1m3QYazxmWL8gkgxYZQuwx5Ic/edit?usp=sharing

You may want to skip to "Creating a customized child template."
