### ISSUE TITLE
The tree view on the left hand side of the page

### ISSUE THREAD

**Issue by kpturner** [hegemonic/jsdoc-baseline#148]
On the left hand side of the page there appears to be a treeview.  Would would normally expected to appear in that section?   For me I only see one top level class, but nothing below or indented to go with it.   Also I have three separate namespaces, but these do not seem to appear in a way that allows me to see what belongs to each namespace.  Is that expected behaviour?

![image](https://cloud.githubusercontent.com/assets/308646/6554767/1f771762-c657-11e4-8353-2a81d8610048.png)

**Comment by hegemonic** [comment]
Try clicking the arrow next to `RNS`. That should expand the next level of the tree view.

**Comment by kpturner** [comment]
Ahh yes, so what I should really be asking is:
1) How to have the cursor change when the mouse hovers over the arrow (so you know it is clickable) and
2) How to have the tree view auto-expanded on initial load.

I will have a poke about and see if I can customise it locally

**Comment by kpturner** [comment]
....although I see it remembers your last setting for the tree view so that is good.

**Comment by kpturner** [comment]
I changed the .jqtree-toggler class to include cursor: pointer
