### ISSUE TITLE
example tag not functioning as expected

### ISSUE THREAD

**Issue by jobalexander** [hegemonic/jsdoc-baseline#151]
/** @function module:table.caption
       * @param {string} [_x] - Sets value of {@link module:table~caption caption} to _x. If parameter missing then returns current value of {@link module:table~caption caption}.
       * @description Setter/getter function for {@link module:table~caption caption}.
       * @example 
       * <caption>Assume that the table module is referenced as table in the main.js file.</caption>
       * var example_table = table();
       * example_table.caption("Example Table");
       *
       * //returns "Example Table"
       * example_table.caption();
       * */ 

returns the following:
![caption](https://cloud.githubusercontent.com/assets/1398747/7036578/ac6864c2-dd4b-11e4-9ce9-01ab80643501.jpg)

Sorry if this has already been addressed but a quick search through the issues did not result in any obvious hits.

**Comment by hegemonic** [comment]
Confirmed. I'm investigating. Sorry for the lengthy delay.

**Comment by hegemonic** [comment]
Fixed on master. If you run into any other issues with this, please feel free to file a new bug!
