### ISSUE TITLE
Namespaces on HOME page are not logically ordered / misplaced / confusing

### ISSUE THREAD

**Issue by SunboX** [hegemonic/jsdoc-baseline#159]
See screenshot:

![namespaces](https://cloud.githubusercontent.com/assets/83344/7705480/b8ee5ce6-fe44-11e4-917a-6de90272bb2f.PNG)

**Comment by hegemonic** [comment]
Yep, this doesn't look right. This issue is related to #144.

**Comment by hegemonic** [comment]
This should be fixed on master. Please take a look. If there's anything that still looks weird, I'd be happy to reopen this issue.
