### ISSUE TITLE
Duplicated headline

### ISSUE THREAD

**Issue by SunboX** [hegemonic/jsdoc-baseline#164]
The headline `new Registration()` is duplicated in this case.

## Sample
```js
/**
 * Text
 *
 * @class
 * @memberof xxx
 */
xxx.Registration = (function() {

    /**
     * @constructs xxx.Registration
     */
    var Registration = function() {};

    return Registration;

})();
```

## Gnerated docs
![headline](https://cloud.githubusercontent.com/assets/83344/7855013/97386070-051e-11e5-83c9-905709fcb09e.PNG)

**Comment by hegemonic** [comment]
This is the expected behavior--the same thing happens with JSDoc's default template. The issue is that you've effectively documented the constructor twice.

You can solve this issue by documenting the constructor just once:

```js
xxx.Registration = (function() {

    /**
     * Text
     *
     * @class
     * @memberof xxx
     */
    var Registration = function() {};

    return Registration;

})();
```

**Comment by SunboX** [comment]
Thanks for the hint! :smile:
