### ISSUE TITLE
{@link xxx.Yyy} in @param description not linked

### ISSUE THREAD

**Issue by SunboX** [hegemonic/jsdoc-baseline#165]
`@link` in `@param` description won't be linked.

```js
/**
 * @param {xxx.Remote~requestCallback} callback - callback used upon response. Called with {@link xxx.ServiceResult}
 */
```

**Comment by hegemonic** [comment]
I can't reproduce this issue. When I run the following code through the Baseline template, the link to `doThing` works correctly:

```js
/**
 * Do a thing.
 */
function doThing() {}

/**
 * Do another thing.
 * @param {string} blah - Takes a param, unlike {@link doThing}
 */
function doAnotherThing(blah) {}
```

The most likely explanation is that you're using the wrong namepath in the link, and that `xxx.ServiceResult` actually has some other name.

**Comment by SunboX** [comment]
Oh, you are right! :cry: I had mistyped something. Sorry for the issue!
