### ISSUE TITLE
Weird "Global" definitions 

### ISSUE THREAD

**Issue by kpturner** [hegemonic/jsdoc-baseline#176]
I am documenting node application, and using an example like this:

```
 var node_cryptojs =  require('node-cryptojs-aes');
 var crypto = require('crypto');
 var CryptoJS = node_cryptojs.CryptoJS;
 var randomstring=require('randomstring');
 var trim=require('trim'); 
 module.exports = { 
 }
```

the `node_cryptojs` variable gets labelled as a `Global` in the docs.  Fair enough I guess, but why do none of the other global definitions also appear in the same `Global` location?

**Comment by hegemonic** [comment]
I can't reproduce this issue with the current versions of JSDoc and Baseline.
