### ISSUE TITLE
font URL returning 503 backend unhealthy

### ISSUE THREAD

**Issue by bcoe** [hegemonic/jsdoc-baseline#192]
The font URL https://brick.a.ssl.fastly.net/Inconsolata:500 is returning a `503 backend unhealthy`, which is in turn breaking unit tests.

Any thoughts on how to best address this issue? Is a backing service perhaps down.

**Comment by hegemonic** [comment]
Looks like this is working again, but I'm going to remove the dependency on the external service so this issue doesn't recur.

**Comment by bcoe** [comment]
@hegemonic thank you for digging into this.
